version: '3.3'

services:
  dbreact:
    container_name: dbreactttt
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ttt
      MYSQL_DATABASE: MYSQL_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "6606:6606"

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8001:80" # เปลี่ยนพอร์ตจาก 8000 เป็น 8001
    restart: always
    environment:
      PMA_HOST: dbreact
    depends_on:
      - dbreact

  php-apache-environment:
    container_name: php-apachettt
    build:
      context: ./php
      dockerfile: Dockerfile
    depends_on:
      - dbreact
    volumes:
      - ./php/src:/var/www/html/
    ports:
      - 8081:80 # เปลี่ยนพอร์ตจาก 8080 เป็น 8081
